### PR TITLE
Remove logger.exception on expected exceptions

### PR DESCRIPTION
**Pull request by wolever**
Currently `logger.exception(…)` is called on exceptions that are expected to happen (ex, 404 errors, or retries exceeded), and re-raised back into user code. This pollutes application logs and is generally unhelpful.

### CODE REVIEW

**Comment by openstack-gerrit** [comment]
Thank you for contributing to openstack/python-swiftclient!

openstack/python-swiftclient uses Gerrit for code review.

If you have never contributed to OpenStack before make sure you have read the
getting started documentation:
http://docs.openstack.org/infra/manual/developers.html#getting-started

Otherwise please visit
http://docs.openstack.org/infra/manual/developers.html#development-workflow
and follow the instructions there to upload your change to Gerrit.

**Comment by clayg** [comment]
yay process!  After awhile the Gerrit thing get's easier - sometimes you don't even notice the infinite sadness.  If you're super down on it you should tweet at ... idk some openstack community/process/foundation person - maybe @Thingee

FWIW, this probably wouldn't fly as-is anyway since (as stated in the launchpad bug for the issue [1]) it's basically a direct revert of the original attempt to improve debug logging [2] which was a fix for another bug that swiftclient wasn't logging *enough* [3]

1. https://bugs.launchpad.net/bugs/1213179
2. https://review.openstack.org/#/c/37336/ 
3. https://bugs.launchpad.net/python-swiftclient/+bug/1202229

**Comment by wolever** [comment]
This is the point, then, where I throw in the towel.

My fix — `logger.exception = logger.info` — is good enough, and to be frank: the shits I have to give could be better spent on projects that aren't [32 open reviews * 19 days / review = 608 days behind](http://stackalytics.com/report/reviews/python-swiftclient/open) on accepting patches.

**Comment by saaros** [comment]
FWIW PGHoard also faced this issue, we worked around it by monkey patching swiftclient's exception logging: https://github.com/ohmu/pghoard/commit/ad1a91b929b261779a714830558c72c22b2ee9af

PGHoard is a PostgreSQL backup and recovery daemon which stores PostgreSQL's write-ahead-log segments in an object store archive.  PostgreSQL may and will request non-existent segments from the archive so just in normal operation we'd get tons of unnecessary logs for 404s.

**Pull request closed without merging**
